## Multinomial and Bernoulli Naive Bayes

For understanding Multinomial and Bernoulli Naive Bayes, we will start with a small example and understand the end to end process. In another notebook, we will build a full-fledged email spam classifier.

To start with, let's take a few sentences and classify them in two different classes - *education* or *cinema*. Each sentence will represent one document. In real-world cases, a document be any piece of text such as an email, a news article, a book review, a tweet etc.
The analysis and the algorithm involved doesn’t depend on the type of document we use.

The notebook is divided into the following sections:
1. Importing and preprocessing data
2. Building the model: Multinomial Naive Bayes
3. Building the model: Bernoulli Naive Bayes

### 1. Importing and Preprocessing Data

Let us first look at the sentences and their classes. We have kept the training sentences in file example_train.csv. Test sentences have been put in the file example_test.csv.

In [76]:
import numpy as np
import pandas as pd
import sklearn

# training data
train_docs = pd.read_csv('movie_review_train.csv') 
train_docs

class                                               text
0      Pos   a common complaint amongst film critics is   ...
1      Pos   whew   this film oozes energy   the kind of b...
2      Pos   steven spielberg s   amistad     which is bas...
3      Pos   he has spent his entire life in an awful litt...
4      Pos   being that it is a foreign language film with...
...    ...                                                ...
1595   Neg   if anything     stigmata   should be taken as...
1596   Neg   john boorman s   zardoz   is a goofy cinemati...
1597   Neg   the kids in the hall are an acquired taste   ...
1598   Neg   there was a time when john carpenter was a gr...
1599   Neg   two party guys bob their heads to haddaway s ...

[1600 rows x 2 columns]

So as you can see there are 5 documents (sentences) , 3 are of "education" class and 2 are of "cinema" class.

In [77]:
# convert label to a numerical variable
train_docs['class'] = train_docs['class'].map({'Neg':0,'Pos':1})
train_docs

class                                               text
0         1   a common complaint amongst film critics is   ...
1         1   whew   this film oozes energy   the kind of b...
2         1   steven spielberg s   amistad     which is bas...
3         1   he has spent his entire life in an awful litt...
4         1   being that it is a foreign language film with...
...     ...                                                ...
1595      0   if anything     stigmata   should be taken as...
1596      0   john boorman s   zardoz   is a goofy cinemati...
1597      0   the kids in the hall are an acquired taste   ...
1598      0   there was a time when john carpenter was a gr...
1599      0   two party guys bob their heads to haddaway s ...

[1600 rows x 2 columns]

Let's now split the dataframe into X and y labels.

In [78]:
# convert the df to a numpy array 
train_array = train_docs.values

# split X and y
X_train = train_array[:,1]
y_train = train_array[:,0]
y_train = y_train.astype('int') # sklearn needs y as integers

#print("X_train")
#print(X_train)
#print("y_train")
#print(y_train)

### Creating the Bag of Words Representation

We now have to convert the data into a format which can be used for training the model. We'll use the **bag of words representation** for each sentence (document).

Imagine breaking X in individual words and putting them all in a bag. Then we pick all the unique words from the bag one by one and make a dictionary of unique words. 

This is called **vectorization of words**. We have the class ```CountVectorizer()``` in scikit learn to vectorize the words. 


In [79]:
# create an object of CountVectorizer() class 
from sklearn.feature_extraction.text import CountVectorizer 
#help(CountVectorizer)

```Countvectorizer()``` has converted the documents into a set of unique words alphabetically sorted and indexed.


**Stop Words**

We can see a few trivial words such as  'and','is','of', etc. These words don't really make any difference in classyfying a document. These are called **stop words**. So we would like to get rid of them. 

We can remove them by passing a parameter stop_words='english' while instantiating ```Countvectorizer()``` as follows: 

In [80]:
# fitting the vectorizer on training data again
# removing the stop words this time
vec = CountVectorizer(stop_words='english', min_df=.03, max_df=.8)
vec.fit(X_train)
len(vec.vocabulary_)

1643

Notice that the vocabulary has reduced to 12 from 15. Another way of printing the 'vocabulary' is as follows:

In [81]:
# printing feature names
#print(vec.get_feature_names())
#print(len(vec.get_feature_names()))

So our final dictionary is made of 12 words (after discarding the stop words). Now, to do classification, we need to represent all the documents with these words (or tokens) as features. 

Every document will be converted into a *feature vector* representing presence of these words in that document. Let's convert each of our training documents in to a feature vector.

In [82]:
# another way of representing the features
X_transformed = vec.transform(X_train)
X_transformed

<1600x1643 sparse matrix of type '<class 'numpy.int64'>'
	with 217396 stored elements in Compressed Sparse Row format>

You can see X_tranformed is a 5 x 12 **sparse matrix**. It has 5 rows for each of our 5 documents and 12 columns each 
for one word of the dictionary which we just created. Let us print X_transformed.

In [83]:
#print(X_transformed)

This representation can be understood as follows:

Consider first 4 rows of the output: (0,2), (0,5), (0,7) and (0,11). It says that the first document (index 0) has 
7th , 2nd , 5th and 11th 'word' present in the document, and that they appear only
once in the document- indicated by the right hand column entry. 

Similarly, consider the entry (4,4) (third from bottom). It says that the fifth document has the fifth word present twice. Indeed, the 5th word('good') appears twice in the 5th document. 

In real problems, you often work with large documents and vocabularies, and each document contains only a few words in the vocabulary. So it would be a waste of space to store the vocabulary in a typical dataframe, since most entries would be zero. Also, matrix products, additions etc. are much faster with sparse matrices. That's why we use sparse matrices to store the data.


Let us convert this sparse matrix into a more easily interpretable array:

In [126]:
# converting transformed matrix back to an array
# note the high number of zeros
X_transformed.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

To make the dataset more readable, let us examine the vocabulary and the document-term matrix together in a pandas dataframe. The way to convert a matrix into a dataframe is ```pd.DataFrame(matrix, columns=columns)```.


In [85]:
# converting matrix to dataframe
pd.DataFrame(X_transformed.toarray(), 
             columns=vec.get_feature_names())

000  10  100  13  15  1995  1996  1997  1998  1999  ...  written  wrong  \
0       0   0    0   0   1     0     0     0     0     0  ...        0      0   
1       0   0    0   0   0     0     0     0     0     0  ...        0      0   
2       0   0    0   0   0     0     0     0     0     0  ...        0      1   
3       0   0    0   0   0     0     0     0     0     0  ...        0      0   
4       0   1    0   0   0     0     0     0     0     0  ...        0      0   
...   ...  ..  ...  ..  ..   ...   ...   ...   ...   ...  ...      ...    ...   
1595    0   0    0   0   0     0     0     0     0     0  ...        0      0   
1596    0   0    0   0   0     0     0     0     0     0  ...        0      0   
1597    0   0    0   0   0     0     0     0     0     0  ...        0      0   
1598    0   0    0   0   0     2     1     0     0     0  ...        1      1   
1599    0   0    0   0   0     0     0     0     0     0  ...        0      0   

      wrote  yeah  year  years  yes  york  young  younger  
0         0     0     0      3    0     0      0        0  
1         0     0     0      0    1     0      0        0  
2         0     0     1      0    0     0      0        0  
3         0     0     0      1    0     0      1        0  
4         0     0     0      0    0     0      0        0  
...     ...   ...   ...    ...  ...   ...    ...      ...  
1595      0     0     2      0    1     0      0        0  
1596      0     0     1      1    0     0      0        0  
1597      0     0     0      0    0     0      0        0  
1598      0     0     0      0    0     0      0        0  
1599      0     0     0      0    0     0      0        0  

[1600 rows x 1643 columns]

This table shows how many times a particular word occurs in document. In other words, this is a frequency table of the words.

A corpus of documents can thus be represented by a matrix with one row per document and one column per
token (e.g. word) occurring in the corpus.

Let's now import and transform the test data as well.

In [86]:
# test data
test_docs = pd.read_csv('movie_review_test.csv') 
test_docs

class                                               text
0     Pos   films adapted from comic books have had plent...
1     Pos   every now and then a movie comes along from a...
2     Pos   you ve got mail works alot better than it des...
3     Pos      jaws   is a rare film that grabs your atte...
4     Pos   moviemaking is a lot like being the general m...
..    ...                                                ...
395   Neg   one of the first films of 1999 is this mtv pi...
396   Neg   susan granger s review of   america s sweethe...
397   Neg   susan granger s review of   jeepers creepers ...
398   Neg   this independent film written and directed by...
399   Neg   come on hollywood   surprise me    stop givin...

[400 rows x 2 columns]

In [87]:
# convert label to a numerical variable
test_docs['class'] = test_docs['class'].map({'Neg':0, 'Pos':1})
test_docs.isnull().sum()

class    0
text     0
dtype: int64

In [88]:
# convert to numpy array
test_numpy_array = test_docs.values
#test_numpy_array

In [89]:


# split into X and y
X_test = test_numpy_array[:,1]
y_test = test_numpy_array[:,0]

#print("X_test")
#print(X_test)
#print("y_test")
#print(y_test)

In [91]:
# transform the test data
# note that you *never* fit on test data, only on training data
# and only transform the test data
X_test_transformed = vec.transform(X_test)
X_test_transformed

<400x1643 sparse matrix of type '<class 'numpy.int64'>'
	with 51663 stored elements in Compressed Sparse Row format>

In [92]:
# convert to non-sparse array
#X_test=X_test_transformed.toarray()
#X_test.shape

(400, 1643)

In [93]:
#arr=X_test.flatten()
#arr.shape

(657200,)

In [94]:
#xxx=[i for i in arr if i!=0]
#len(xxx)

51663

Let us summarise all we have done till now:

- ```vect.fit(train)``` learns the vocabulary of the training data
- ```vect.transform(train)``` uses the fitted vocabulary to build a document-term matrix from the training data
- ```vect.transform(test)``` uses the fitted vocabulary to build a document-term matrix from the testing data (and ignores tokens it hasn't seen before)

### 3. Building the Model: Bernoulli Naive Bayes

In [95]:
from sklearn.naive_bayes import BernoulliNB

# instantiating bernoulli NB class
bnb=BernoulliNB()

# fitting the model
bnb.fit(X_transformed, y_train)



BernoulliNB()

In [129]:



# predict class
y_pred_class = bnb.predict(X_test_transformed.toarray())

# predict probability
y_pred_proba =bnb.predict_proba(X_test_transformed)
y_pred_class


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 2, 0]], dtype=int64)

In [97]:
y_pred_class

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,

In [110]:
y_test.shape

(400,)

In [123]:
yyy=(yy_test.values).flatten()
yyy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [104]:
from sklearn import metrics
metrics.accuracy_score(yyy, y_pred_class)

ValueError: Expected array-like (array or non-string sequence), got None

In [ ]:
y_test.is